src/components/article/article-form.tsx, src/components/article/article-list.tsx, src/components/article/article-router.tsx, src/components/article/views/article-edit-form-view.tsx, src/components/currency/currency-input.tsx, src/store/reducers/__tests__/article.spec.ts, src/store/reducers/article.ts
=> feat(articleForm): add edit articles

src/components/user-details/user-details-header.tsx
=> feat(user-details-header): add toggle feature

src/components/user/views/user-article-transaction.tsx
=> fix(user-article-transaction): do not rely on goBack on success

src/components/user/user-details.tsx, src/locales/en.ts
=> feat(user-details):  add transactions empty state

src/components/user/create-user-inline-form.tsx
=> fix(create-user-inline-form): add explixit width to input

src/components/transaction/create-user-transaction-form.tsx
=> fix(create-user-transaction-form): add focus to submit button

src/components/article/article-form.tsx
=> fix(article-form): add basic responsiveness for mobile

src/components/transaction/transaction-table.tsx
=> fix(transaction-table): decrease limit to 5

src/components/article/article-form.tsx
=> fix(article-form): align grid

src/components/article/__tests__/validator.spec.tsx, src/components/article/article-form.tsx, src/components/article/article-selection-bubbles.tsx, src/components/article/validator.tsx, src/components/transaction/create-custom-transaction-form.tsx, src/components/transaction/payment-button-steps.tsx, src/components/transaction/payment.tsx, src/components/transaction/transaction-table.tsx, src/components/transaction/user-to-user-validator.tsx, src/components/transaction/validator.tsx, src/components/user/views/user-article-transaction.tsx, src/components/user/views/user.tsx, src/store/reducers/__tests__/transaction.spec.ts, src/store/reducers/setting.ts, src/store/reducers/transaction.ts
closes #99 
closes #97 
closes #100
=> Article amount validator

src/app.tsx, src/components/common/header-menu.tsx, src/components/common/idle-timer.tsx, src/components/transaction/index.ts, src/components/transaction/split-invoice/index.ts, src/components/transaction/split-invoice/split-invoice.tsx, src/components/user/user-selection.tsx, src/store/reducers/__tests__/user.spec.ts, src/store/reducers/user.ts
=> Split invoice

.editorconfig, src/components/currency/__tests__/__snapshots__/currency-input.spec.tsx.snap, src/components/currency/currency-input.tsx, src/components/transaction/__tests__/__snapshots__/create-custom-transactions-form.spec.tsx.snap, src/components/transaction/__tests__/user-to-user-validator.spec.tsx, src/components/transaction/user-to-user-validator.tsx, src/components/ui/theme.ts
=> 121 ui improvments

src/components/article/article-selection-bubbles.tsx, src/store/reducers/__tests__/__snapshots__/article.spec.ts.snap, src/store/reducers/article.ts
=> Fix article issues

src/components/user-details/user-details-header.tsx, src/components/user/create-user-inline-form.tsx, src/components/user/edit-user-form.tsx, src/components/user/views/user-edit-view.tsx
closes #126 
closes #125 
closes #124
=> Fix user issues

src/components/transaction/create-user-transaction-form.tsx
closes #131 
completely messed this up last time. 
Now it should be working for real 📦
=> fix(create-user-transaction-form): improve form submit handling

src/components/transaction/create-user-transaction-form.tsx
=> fix(create-user-transaction-form): remove doubled event listener

package.json, src/components/article/article-form.tsx, src/components/article/views/article-edit-form-view.tsx, yarn.lock
Close article edit form on click outside :)
=> feat(article-form): close edit view on click outside

src/components/ui/theme.ts
=> fix(theme): remove force scroll

src/app.tsx, src/components/transaction/__tests__/__snapshots__/create-custom-transactions-form.spec.tsx.snap, src/components/transaction/create-custom-transaction-form.tsx, src/components/ui/theme.ts
=> 121 ui improvements

src/app.tsx, src/components/settings/scaling-buttons.tsx, src/components/ui/footer.tsx, src/components/ui/theme.ts, src/hooks/use-storage.ts
=> feat(Scaling): add dynamic app scaling for touch devices

src/components/common/scroll-to-top.ts, src/components/user/views/transaction-overview.tsx, src/components/user/views/user.tsx
always scroll to top on user overview and transaction overview
closes #157
=> feat(scroll-to-top): add router scroll component

src/components/article/article-selection-bubbles.tsx, src/components/currency/__tests__/__snapshots__/currency.spec.tsx.snap, src/components/currency/__tests__/currency.spec.tsx, src/components/currency/currency.tsx
=> fix(currency): + sign should be optional

package.json, src/components/transaction/__tests__/__snapshots__/create-custom-transactions-link.spec.tsx.snap, src/components/user/user-details.tsx, src/components/user/user-selection.tsx, tsconfig.json, yarn.lock
=> 171 remove focus

src/components/transaction/create-custom-transaction-form.tsx, src/components/transaction/payment.tsx, src/components/user/user-details.module.css, src/components/user/user-details.tsx, src/store/reducers/__tests__/transaction.spec.ts, src/store/reducers/setting.ts, src/store/reducers/transaction.ts, src/store/selector-hooks.ts
closes #170 
closes #169
thanks for the catch :)
=> fix(setting): implement feature flags

src/components/metrics/metrics.tsx, src/components/metrics/resource.ts
closes #178 
is working with staging api :)
=> fix(metrics): updated api

package.json, src/components/article/article-form.tsx, src/components/article/article-list.tsx, src/components/article/article-router.tsx, src/components/article/article-selection-bubbles.tsx, src/components/ui/icons/trash.tsx, src/hooks/use-toggle.ts, src/locales/en.ts, src/store/reducers/__tests__/article.spec.ts, src/store/reducers/article.ts, src/store/selector-hooks.ts, yarn.lock
closes #155 
but there is one backend issue.
It looks like the article pagination is not working. 
So there is never the chance to return not active articles.
Could be usefull if someone wants to reenable an article. 
An api for that would be nice as well
=> feat(article-list): add delete article

src/components/common/scanner.tsx
=> fix(scanner): remove focus before submiting scan

src/components/metrics/user-metrics/metrics.tsx, src/components/metrics/user-metrics/resource.ts, src/components/user-details/user-details-header.tsx, src/components/user/user-list.tsx, src/store/reducers/__tests__/__snapshots__/setting.spec.ts.snap, src/store/reducers/setting.ts, src/store/selector-hooks.ts
=> 166 article setting

src/app.tsx, src/components/common/header-menu.tsx, src/components/common/search-list/search-list.tsx, src/components/common/search-results/index.ts, src/components/common/search-results/search-result-item/search-result-item.tsx, src/components/common/search-results/search-results.tsx, src/components/ui/icons/logo.tsx, src/components/ui/icons/search.tsx, src/components/user/user-list.tsx, src/components/user/user-router.tsx
=> 187 search field improvements

src/components/paypal/paypal-transaction-form.tsx
=> fix(paypal-transaction-form): set rm to 1

src/components/user-details/user-details-header.module.css, src/components/user/user-name.module.css
=> chore: update user-name to allow longer names
